name: iOS Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci
        continue-on-error: false

      - name: TypeScript type check
        run: |
          npx tsc --noEmit
        continue-on-error: false

      - name: Run tests
        run: |
          npm test -- --watchAll=false --coverage=false
        continue-on-error: false

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: ios

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install --repo-update
        continue-on-error: false

      - name: Cache Xcode derived data
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-xcode-${{ hashFiles('ios/**/*.xcodeproj/project.pbxproj') }}
          restore-keys: |
            ${{ runner.os }}-xcode-

      - name: Build iOS Archive
        run: |
          cd ios
          xcodebuild \
            -workspace Evie.xcworkspace \
            -scheme Evie \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath build/Evie.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO
        continue-on-error: false

      - name: Export IPA
        run: |
          cd ios
          
          # Create export options plist
          cat > ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
          </dict>
          </plist>
          EOF
          
          # Export IPA
          xcodebuild \
            -exportArchive \
            -archivePath build/Evie.xcarchive \
            -exportPath build \
            -exportOptionsPlist ExportOptions.plist \
            -allowProvisioningUpdates
        continue-on-error: false

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-${{ github.run_number }}
          path: |
            ios/build/*.ipa
            ios/build/Evie.xcarchive
          retention-days: 30
        if: success()

      - name: Upload build logs on failure
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ github.run_number }}
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/Logs
            ios/build/Logs
          retention-days: 7
        if: failure()

      - name: Build summary
        run: |
          echo "## iOS Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Number**: ${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          if [ -f "ios/build/Evie.ipa" ]; then
            echo "- **IPA Size**: $(du -h ios/build/Evie.ipa | cut -f1)" >> $GITHUB_STEP_SUMMARY
          fi
        if: always()